// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendEvent.proto

package com.rokid.proto;

public final class SendEvent {
    private SendEvent() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface SendEventRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string cloudAppId = 1;

        /**
         * <code>required string cloudAppId = 1;</code>
         */
        boolean hasAppId();

        /**
         * <code>required string cloudAppId = 1;</code>
         */
        String getAppId();

        /**
         * <code>required string cloudAppId = 1;</code>
         */
        com.google.protobuf.ByteString
        getAppIdBytes();

        // required string event = 2;

        /**
         * <code>required string event = 2;</code>
         */
        boolean hasEvent();

        /**
         * <code>required string event = 2;</code>
         */
        String getEvent();

        /**
         * <code>required string event = 2;</code>
         */
        com.google.protobuf.ByteString
        getEventBytes();

        // required string extra = 3;

        /**
         * <code>required string extra = 3;</code>
         */
        boolean hasExtra();

        /**
         * <code>required string extra = 3;</code>
         */
        String getExtra();

        /**
         * <code>required string extra = 3;</code>
         */
        com.google.protobuf.ByteString
        getExtraBytes();
    }

    /**
     * Protobuf type {@code proto.SendEventRequest}
     */
    public static final class SendEventRequest extends
            com.google.protobuf.GeneratedMessage
            implements SendEventRequestOrBuilder {
        // Use SendEventRequest.newBuilder() to construct.
        private SendEventRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private SendEventRequest(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final SendEventRequest defaultInstance;

        public static SendEventRequest getDefaultInstance() {
            return defaultInstance;
        }

        public SendEventRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private SendEventRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            appId_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            event_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            extra_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return SendEvent.internal_static_proto_SendEventRequest_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return SendEvent.internal_static_proto_SendEventRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            SendEventRequest.class, Builder.class);
        }

        public static com.google.protobuf.Parser<SendEventRequest> PARSER =
                new com.google.protobuf.AbstractParser<SendEventRequest>() {
                    public SendEventRequest parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new SendEventRequest(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<SendEventRequest> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // required string cloudAppId = 1;
        public static final int APPID_FIELD_NUMBER = 1;
        private Object appId_;

        /**
         * <code>required string cloudAppId = 1;</code>
         */
        public boolean hasAppId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string cloudAppId = 1;</code>
         */
        public String getAppId() {
            Object ref = appId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    appId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string cloudAppId = 1;</code>
         */
        public com.google.protobuf.ByteString
        getAppIdBytes() {
            Object ref = appId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                appId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string event = 2;
        public static final int EVENT_FIELD_NUMBER = 2;
        private Object event_;

        /**
         * <code>required string event = 2;</code>
         */
        public boolean hasEvent() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string event = 2;</code>
         */
        public String getEvent() {
            Object ref = event_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    event_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string event = 2;</code>
         */
        public com.google.protobuf.ByteString
        getEventBytes() {
            Object ref = event_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                event_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string extra = 3;
        public static final int EXTRA_FIELD_NUMBER = 3;
        private Object extra_;

        /**
         * <code>required string extra = 3;</code>
         */
        public boolean hasExtra() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string extra = 3;</code>
         */
        public String getExtra() {
            Object ref = extra_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    extra_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string extra = 3;</code>
         */
        public com.google.protobuf.ByteString
        getExtraBytes() {
            Object ref = extra_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                extra_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            appId_ = "";
            event_ = "";
            extra_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasAppId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasEvent()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasExtra()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getAppIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getEventBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getExtraBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getAppIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getEventBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getExtraBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static SendEventRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static SendEventRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static SendEventRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static SendEventRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static SendEventRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static SendEventRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static SendEventRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static SendEventRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static SendEventRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static SendEventRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(SendEventRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code proto.SendEventRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements SendEventRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return SendEvent.internal_static_proto_SendEventRequest_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return SendEvent.internal_static_proto_SendEventRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                SendEventRequest.class, Builder.class);
            }

            // Construct using com.rokid.cloudappclient.proto.SendEvent.SendEventRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                appId_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                event_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                extra_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return SendEvent.internal_static_proto_SendEventRequest_descriptor;
            }

            public SendEventRequest getDefaultInstanceForType() {
                return SendEventRequest.getDefaultInstance();
            }

            public SendEventRequest build() {
                SendEventRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public SendEventRequest buildPartial() {
                SendEventRequest result = new SendEventRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.appId_ = appId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.event_ = event_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.extra_ = extra_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof SendEventRequest) {
                    return mergeFrom((SendEventRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(SendEventRequest other) {
                if (other == SendEventRequest.getDefaultInstance())
                    return this;
                if (other.hasAppId()) {
                    bitField0_ |= 0x00000001;
                    appId_ = other.appId_;
                    onChanged();
                }
                if (other.hasEvent()) {
                    bitField0_ |= 0x00000002;
                    event_ = other.event_;
                    onChanged();
                }
                if (other.hasExtra()) {
                    bitField0_ |= 0x00000004;
                    extra_ = other.extra_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasAppId()) {

                    return false;
                }
                if (!hasEvent()) {

                    return false;
                }
                return hasExtra();
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                SendEventRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (SendEventRequest) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // required string cloudAppId = 1;
            private Object appId_ = "";

            /**
             * <code>required string cloudAppId = 1;</code>
             */
            public boolean hasAppId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string cloudAppId = 1;</code>
             */
            public String getAppId() {
                Object ref = appId_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    appId_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string cloudAppId = 1;</code>
             */
            public com.google.protobuf.ByteString
            getAppIdBytes() {
                Object ref = appId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    appId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string cloudAppId = 1;</code>
             */
            public Builder setAppId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                appId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string cloudAppId = 1;</code>
             */
            public Builder clearAppId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                appId_ = getDefaultInstance().getAppId();
                onChanged();
                return this;
            }

            /**
             * <code>required string cloudAppId = 1;</code>
             */
            public Builder setAppIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                appId_ = value;
                onChanged();
                return this;
            }

            // required string event = 2;
            private Object event_ = "";

            /**
             * <code>required string event = 2;</code>
             */
            public boolean hasEvent() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string event = 2;</code>
             */
            public String getEvent() {
                Object ref = event_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    event_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string event = 2;</code>
             */
            public com.google.protobuf.ByteString
            getEventBytes() {
                Object ref = event_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    event_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string event = 2;</code>
             */
            public Builder setEvent(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                event_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string event = 2;</code>
             */
            public Builder clearEvent() {
                bitField0_ = (bitField0_ & ~0x00000002);
                event_ = getDefaultInstance().getEvent();
                onChanged();
                return this;
            }

            /**
             * <code>required string event = 2;</code>
             */
            public Builder setEventBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                event_ = value;
                onChanged();
                return this;
            }

            // required string extra = 3;
            private Object extra_ = "";

            /**
             * <code>required string extra = 3;</code>
             */
            public boolean hasExtra() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string extra = 3;</code>
             */
            public String getExtra() {
                Object ref = extra_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    extra_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string extra = 3;</code>
             */
            public com.google.protobuf.ByteString
            getExtraBytes() {
                Object ref = extra_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    extra_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string extra = 3;</code>
             */
            public Builder setExtra(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                extra_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string extra = 3;</code>
             */
            public Builder clearExtra() {
                bitField0_ = (bitField0_ & ~0x00000004);
                extra_ = getDefaultInstance().getExtra();
                onChanged();
                return this;
            }

            /**
             * <code>required string extra = 3;</code>
             */
            public Builder setExtraBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                extra_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:proto.SendEventRequest)
        }

        static {
            defaultInstance = new SendEventRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:proto.SendEventRequest)
    }

    public interface SendEventResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string response = 1;

        /**
         * <code>required string response = 1;</code>
         */
        boolean hasResponse();

        /**
         * <code>required string response = 1;</code>
         */
        String getResponse();

        /**
         * <code>required string response = 1;</code>
         */
        com.google.protobuf.ByteString
        getResponseBytes();
    }

    /**
     * Protobuf type {@code proto.SendEventResponse}
     */
    public static final class SendEventResponse extends
            com.google.protobuf.GeneratedMessage
            implements SendEventResponseOrBuilder {
        // Use SendEventResponse.newBuilder() to construct.
        private SendEventResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private SendEventResponse(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final SendEventResponse defaultInstance;

        public static SendEventResponse getDefaultInstance() {
            return defaultInstance;
        }

        public SendEventResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private SendEventResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            response_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return SendEvent.internal_static_proto_SendEventResponse_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return SendEvent.internal_static_proto_SendEventResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            SendEventResponse.class, Builder.class);
        }

        public static com.google.protobuf.Parser<SendEventResponse> PARSER =
                new com.google.protobuf.AbstractParser<SendEventResponse>() {
                    public SendEventResponse parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new SendEventResponse(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<SendEventResponse> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // required string response = 1;
        public static final int RESPONSE_FIELD_NUMBER = 1;
        private Object response_;

        /**
         * <code>required string response = 1;</code>
         */
        public boolean hasResponse() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string response = 1;</code>
         */
        public String getResponse() {
            Object ref = response_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    response_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string response = 1;</code>
         */
        public com.google.protobuf.ByteString
        getResponseBytes() {
            Object ref = response_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                response_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            response_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasResponse()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getResponseBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getResponseBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static SendEventResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static SendEventResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static SendEventResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static SendEventResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static SendEventResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static SendEventResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static SendEventResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static SendEventResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static SendEventResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static SendEventResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(SendEventResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code proto.SendEventResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements SendEventResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return SendEvent.internal_static_proto_SendEventResponse_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return SendEvent.internal_static_proto_SendEventResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                SendEventResponse.class, Builder.class);
            }

            // Construct using com.rokid.cloudappclient.proto.SendEvent.SendEventResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                response_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return SendEvent.internal_static_proto_SendEventResponse_descriptor;
            }

            public SendEventResponse getDefaultInstanceForType() {
                return SendEventResponse.getDefaultInstance();
            }

            public SendEventResponse build() {
                SendEventResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public SendEventResponse buildPartial() {
                SendEventResponse result = new SendEventResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.response_ = response_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof SendEventResponse) {
                    return mergeFrom((SendEventResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(SendEventResponse other) {
                if (other == SendEventResponse.getDefaultInstance())
                    return this;
                if (other.hasResponse()) {
                    bitField0_ |= 0x00000001;
                    response_ = other.response_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return hasResponse();
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                SendEventResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (SendEventResponse) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // required string response = 1;
            private Object response_ = "";

            /**
             * <code>required string response = 1;</code>
             */
            public boolean hasResponse() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string response = 1;</code>
             */
            public String getResponse() {
                Object ref = response_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    response_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string response = 1;</code>
             */
            public com.google.protobuf.ByteString
            getResponseBytes() {
                Object ref = response_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    response_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string response = 1;</code>
             */
            public Builder setResponse(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                response_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string response = 1;</code>
             */
            public Builder clearResponse() {
                bitField0_ = (bitField0_ & ~0x00000001);
                response_ = getDefaultInstance().getResponse();
                onChanged();
                return this;
            }

            /**
             * <code>required string response = 1;</code>
             */
            public Builder setResponseBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                response_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:proto.SendEventResponse)
        }

        static {
            defaultInstance = new SendEventResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:proto.SendEventResponse)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_SendEventRequest_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_proto_SendEventRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_SendEventResponse_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_proto_SendEventResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\017SendEvent.proto\022\005proto\"?\n\020SendEventReq" +
                        "uest\022\r\n\005appId\030\001 \002(\t\022\r\n\005event\030\002 \002(\t\022\r\n\005ex" +
                        "tra\030\003 \002(\t\"%\n\021SendEventResponse\022\020\n\010respon" +
                        "se\030\001 \002(\tB+\n\036com.rokid.cloudappclient.pro" +
                        "toB\tSendEvent"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_proto_SendEventRequest_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_proto_SendEventRequest_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_proto_SendEventRequest_descriptor,
                                new String[]{"AppId", "Event", "Extra",});
                        internal_static_proto_SendEventResponse_descriptor =
                                getDescriptor().getMessageTypes().get(1);
                        internal_static_proto_SendEventResponse_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_proto_SendEventResponse_descriptor,
                                new String[]{"Response",});
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
